export const CLIENTS = [
  { id: 1,  initials: "TS", color: "#b0b60d", name: "TECNOSUR HIDROGRUAS",    rubro: "Taller reparacion",      ubicacion: "Rada Tilly - Chubut",            logo: "/images/clientes/tecnosur.jpg" },
  { id: 2,  initials: "CA", color: "#23292d", name: "KSK",                    rubro: "Indumentaria",           ubicacion: "Comodoro Rivadavia - Chubut",    logo: "" },
  { id: 3,  initials: "MS", color: "#ebab9b", name: "FRANCA TIENDA DE MAR",   rubro: "Regalería",              ubicacion: "Puerto Pirámides - Chubut",      logo: "/images/clientes/franca.jpg" },
  { id: 4,  initials: "DN", color: "#e79d26", name: "CURTO Propiedades",      rubro: "Inmobiliaria",           ubicacion: "Rada Tilly - Chubut",            logo: "/images/clientes/curto.png" },
  { id: 5,  initials: "CA", color: "#ea4040", name: "Cheeky",                 rubro: "Indumentaria",           ubicacion: "Comodoro Rivadavia - Chubut",    logo: "" },
  { id: 6,  initials: "RC", color: "#b51d0c", name: "Tiziana Deco",           rubro: "Mueblería",              ubicacion: "Comodoro Rivadavia - Chubut",    logo: "/images/clientes/tiziana.jpg" },
  { id: 7,  initials: "CA", color: "#7fa8e0", name: "Hans Sachs",             rubro: "Indumentaria",           ubicacion: "Comodoro Rivadavia - Chubut",    logo: "" },
  { id: 8,  initials: "CS", color: "#73be4a", name: "Lent-Sur",               rubro: "Óptica",                 ubicacion: "Comodoro Rivadavia - Chubut",    logo: "/images/clientes/lentsur.jpg" },
  { id: 9,  initials: "AP", color: "#09984e", name: "Ciudad Inmobiliaria",    rubro: "Inmobiliaria",           ubicacion: "Rada Tilly - Chubut",            logo: "/images/clientes/ciudad.jpg" },
  { id: 10, initials: "FP", color: "#1b0769", name: "Granada",                rubro: "Indumentaria",           ubicacion: "Rada Tilly - Chubut",            logo: "/images/clientes/granada.jpg" },
  { id: 11, initials: "IV", color: "#712a10", name: "Musters",                rubro: "Vinoteca",               ubicacion: "Rada Tilly - Chubut",            logo: "/images/clientes/musters.jpg" },
  { id: 12, initials: "EC", color: "#41c447", name: "Tienda Goy",             rubro: "Indumentaria",           ubicacion: "Comodoro Rivadavia - Chubut",    logo: "" },
  { id: 13, initials: "AC", color: "#e08e2a", name: "IRP Import Racing",      rubro: "Repuestos Automotor",    ubicacion: "CABA - Bs As",                   logo: "" },
  { id: 14, initials: "JA", color: "#ce241b", name: "Pulgarcito",             rubro: "Indumentaria",           ubicacion: "Comodoro Rivadavia - Chubut",    logo: "" },
  { id: 15, initials: "PC", color: "#9e1b1b", name: "New Wine",               rubro: "Vinoteca",               ubicacion: "Comodoro Rivadavia - Chubut",    logo: "" },
  { id: 16, initials: "SZ", color: "#2a9d8f", name: "Lompas",                 rubro: "Indumentaria",           ubicacion: "Comodoro Rivadavia - Chubut",    logo: "" },
  { id: 17, initials: "LE", color: "#a01010", name: "Optica Rada Tilly",      rubro: "Óptica",                 ubicacion: "Rada Tilly - Chubut",            logo: "" },
  { id: 18, initials: "CA", color: "#457b9d", name: "Sport Hits",             rubro: "Indumentaria",           ubicacion: "Comodoro Rivadavia - Chubut",    logo: "" },
  { id: 19, initials: "CA", color: "#b748c6", name: "Clásica y Moderna",      rubro: "Indumentaria",           ubicacion: "Comodoro Rivadavia - Chubut",    logo: "" },
  { id: 20, initials: "CA", color: "#121264", name: "Todo Luz",               rubro: "Electricidad",           ubicacion: "Rada Tilly - Chubut",            logo: "" },
  { id: 21, initials: "CC", color: "#2e4d6b", name: "Carlos Coetsee",         rubro: "Productor de Seguros",   ubicacion: "Rada Tilly - Chubut",            logo: "" },
  { id: 22, initials: "IV", color: "#2f2fbf", name: "Iveco",                  rubro: "Venta de Camiones",      ubicacion: "Rada Tilly - Chubut",            logo: "" },
  { id: 23, initials: "OS", color: "#121217", name: "Ossira",                 rubro: "Indumentaria",           ubicacion: "Comodoro Rivadavia - Chubut",    logo: "" },
  { id: 24, initials: "IN", color: "#21762f", name: "INVAP",                  rubro: "Servicios Petroleros",   ubicacion: "Comodoro Rivadavia - Chubut",    logo: "" },
];
